exp_group:
  - BenchmarkNoNullRelations
models:
  # - BART
  # - llama
  # - RebelBaseline
  - ensemble-36cls
  # - ensemble-11cls
datasets:
  - dialog-re-llama-11cls-rwrtKeys-instrC-mxTrnCp3-skpTps # BenchmarkNoNullRelations
  # - dialog-re-llama-11cls-rebalPairs-rwrtKeys-instrC-mxTrnCp3-skpTps # done!
  # - dialog-re-llama-11cls-rebalPairs3x-rwrtKeys-instrC-mxTrnCp3-skpTps # done!  
  # - dialog-re-ddrel-llama-11cls-rebalPairs3x-rwrtKeys-instrC-mxTrnCp3-shfflDt-skpTps-Ddrl

